services:
  # O Banco de Dados
  db:
    image: postgres:latest
    container_name: linkmanager-demo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: demo_password
      POSTGRES_DB: linkmanager_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_demo_data:/var/lib/postgresql/data

  # A Sua API
  api:
    build: .
    container_name: linkmanager-demo-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Conecta no servi√ßo 'db' definido acima
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=linkmanager_db;Username=postgres;Password=demo_password

volumes:
  postgres_demo_data: