services:
  db-dev:
    image: postgres:16-alpine  # MUDANÇA 1: Versão específica e leve
    container_name: linkmanager-dev-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: linkmanager_dev_db
      PGDATA: /var/lib/postgresql/data/pgdata # MUDANÇA 2: Salvar em subpasta evita erro de "pasta não vazia"
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data: